spring.application.name=sistema-cursos-springboot
#Configuracion para base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#Estableciendo el encoding para tildes y textos latinoamericanos
spring.messages.encoding=UTF-8
#Evitamos conflictos con templates estaticos cuando ocurre un error.
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false